language: java

sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

before_script:
  - cd src/
  - mvn --batch-mode --threads 2.0C -DskipTests=true install

script:
  - mvn --batch-mode --threads 2.0C --show-version clean test

after_success:
  - mvn clean cobertura:cobertura coveralls:report

after_script:
  - cd ..

notifications:
  email:
    on_success: never
    on_failure: never
