language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

before_script:
  - cd src/
  - mvn --batch-mode --threads 2.0C -DskipTests=true -Dmaven.javadoc.skip=true install

script:
  - mvn --batch-mode --threads 2.0C --show-version clean test

after_success:
  - mvn --batch-mode --threads 2.0C clean cobertura:cobertura coveralls:cobertura

after_script:
  - cd ..

notifications:
  email:
    on_success: never
    on_failure: never
